# Generated by Django 5.2.12 on 2026-04-05 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("link_request", "Demande de lien"),
                            ("link_accepted", "Demande acceptée"),
                            ("link_rejected", "Demande refusée"),
                            ("new_report", "Nouveau compte-rendu"),
                            ("recommendation", "Recommandation"),
                            ("mention", "Mention"),
                            ("invitation", "Invitation"),
                            ("new_follower", "Nouveau follower"),
                            ("shared_sequence", "Séquence Partagée"),
                            ("revocation", "Lien révoqué"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(help_text="Human-readable notification text"),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="core_notifi_recipie_1d5476_idx",
                    ),
                    models.Index(
                        fields=["recipient", "type"],
                        name="core_notifi_recipie_b7e00d_idx",
                    ),
                ],
            },
        ),
    ]
