# Generated by Django 5.0.14 on 2026-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contentreport_notificationpreference_userblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='fr', max_length=10)),
                ('registrations_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Instance Settings',
                'verbose_name_plural': 'Instance Settings',
            },
        ),
    ]
