# Generated by Django 5.2.14 on 2026-05-17 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_instancesettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instancesettings",
            name="donation_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable donation prompts based on usage"
            ),
        ),
        migrations.AddField(
            model_name="instancesettings",
            name="donation_prompt_interval",
            field=models.IntegerField(
                default=10, help_text="Show donation prompt every N posts"
            ),
        ),
        migrations.AddField(
            model_name="instancesettings",
            name="donation_url",
            field=models.URLField(
                blank=True, help_text="URL to donation page (Ko-fi, Liberapay, etc.)"
            ),
        ),
        migrations.CreateModel(
            name="DonationPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posts_at_prompt",
                    models.IntegerField(
                        help_text="User's total post count when this prompt was generated"
                    ),
                ),
                (
                    "donated",
                    models.BooleanField(
                        default=False,
                        help_text="True if user donated in response to this prompt",
                    ),
                ),
                ("donated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount_suggested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suggested donation amount based on usage",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserUsageStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_posts", models.IntegerField(default=0)),
                ("total_quotes", models.IntegerField(default=0)),
                ("total_link_requests", models.IntegerField(default=0)),
                ("posts_since_last_prompt", models.IntegerField(default=0)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User usage stats",
                "verbose_name_plural": "User usage stats",
            },
        ),
    ]
