# Generated by Django 5.0.14 on 2026-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_instancesettings_donation_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("link_request", "Demande de lien"),
                    ("link_accepted", "Demande acceptée"),
                    ("link_rejected", "Demande refusée"),
                    ("new_report", "Nouveau compte-rendu"),
                    ("recommendation", "Recommandation"),
                    ("mention", "Mention"),
                    ("invitation", "Invitation"),
                    ("new_follower", "Nouveau follower"),
                    ("shared_sequence", "Séquence Partagée"),
                    ("revocation", "Lien révoqué"),
                    ("muses_suggestion", "Suggestion Muses"),
                ],
                max_length=30,
            ),
        ),
    ]
