# Generated by Django 5.0.14 on 2026-07-19 09:28

from django.db import migrations, models


def purge_muses_suggestion_notifications(apps, schema_editor):
    """Drop orphaned Notification rows whose type is no longer a valid choice.

    CharField choices are not DB-enforced, so rows with type="muses_suggestion"
    (created before the Muses hub removal) would otherwise linger silently.
    """
    Notification = apps.get_model("core", "Notification")
    Notification.objects.filter(type="muses_suggestion").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.RunPython(
            purge_muses_suggestion_notifications, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('link_request', 'Demande de lien'), ('link_accepted', 'Demande acceptée'), ('link_rejected', 'Demande refusée'), ('new_report', 'Nouveau compte-rendu'), ('recommendation', 'Recommandation'), ('mention', 'Mention'), ('invitation', 'Invitation'), ('new_follower', 'Nouveau follower'), ('shared_sequence', 'Séquence Partagée'), ('revocation', 'Lien révoqué')], max_length=30),
        ),
    ]
