# Generated by Django 5.0.14 on 2026-07-19 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('link_request', 'Demande de lien'), ('link_accepted', 'Demande acceptée'), ('link_rejected', 'Demande refusée'), ('new_report', 'Nouveau compte-rendu'), ('recommendation', 'Recommandation'), ('mention', 'Mention'), ('invitation', 'Invitation'), ('new_follower', 'Nouveau follower'), ('shared_sequence', 'Séquence Partagée'), ('revocation', 'Lien révoqué'), ('moderation_report', 'Nouveau signalement à traiter')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harcèlement'), ('inappropriate', 'Contenu inapproprié'), ('other', 'Autre')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('context_object_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu'), ('dismissed', 'Ignoré')], default='pending', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('context_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_userre_status_4e30e9_idx'), models.Index(fields=['reported_user', 'status'], name='core_userre_reporte_cbc839_idx')],
            },
        ),
    ]
