# Generated by Django 5.0.14 on 2026-07-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notification_type_userreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('link_request', 'Demande de lien'), ('link_accepted', 'Demande acceptée'), ('link_rejected', 'Demande refusée'), ('new_report', 'Nouveau compte-rendu'), ('recommendation', 'Recommandation'), ('mention', 'Mention'), ('invitation', 'Invitation'), ('new_follower', 'Nouveau follower'), ('shared_sequence', 'Séquence Partagée'), ('revocation', 'Lien révoqué'), ('moderation_report', 'Nouveau signalement à traiter'), ('offer', 'Nouvelle offre à laquelle répondre'), ('offer_response', 'Votre offre a reçu une réponse'), ('direct_message', 'Message privé')], max_length=30),
        ),
    ]
