# Generated by Django 5.0.14 on 2026-07-20 23:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("link_request", "Demande de lien"),
                    ("link_accepted", "Demande acceptée"),
                    ("link_rejected", "Demande refusée"),
                    ("new_report", "Nouveau compte-rendu"),
                    ("recommendation", "Recommandation"),
                    ("mention", "Mention"),
                    ("invitation", "Invitation"),
                    ("new_follower", "Nouveau follower"),
                    ("shared_sequence", "Séquence Partagée"),
                    ("revocation", "Lien révoqué"),
                    ("moderation_report", "Nouveau signalement à traiter"),
                    ("offer", "Nouvelle offre à laquelle répondre"),
                    ("offer_response", "Votre offre a reçu une réponse"),
                    ("direct_message", "Message privé"),
                    ("achievement", "Succès débloqué"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="UnlockedAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=50)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "seen_at"],
                        name="core_unlock_user_id_0b7fe1_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="unlockedachievement",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="unique_user_achievement"
            ),
        ),
    ]
