# Generated by Django 5.0.14 on 2026-07-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_notification_type_unlockedachievement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userusagestats",
            name="total_quotes",
        ),
    ]
