"""Tests for characters:create — the `create_character_with_sheet` service (Phase 2),
the `character_create` view + URL + payload parsing (Phase 3), and the real
one-page `character_create.html` template (Phase 4). The Alpine.js client-side
serialization (`characterCreate` in frontend/src/main.js) that builds the hidden
`payload` field is not exercised by these server-side tests — POST requests here
submit the payload JSON directly, exactly as the Alpine component would.
"""

from __future__ import annotations

import json
from typing import Any

import pytest
from django.test import Client
from django.urls import resolve, reverse

from suddenly.characters.models import Action, Character, CharacterStatus, Trait, TraitSet
from suddenly.characters.services import create_character_with_sheet
from suddenly.games.models import Game
from suddenly.users.models import User
from tests.factories import GameFactory


def _trait_sets_payload() -> list[dict[str, Any]]:
    return [
        {
            "label": "Corps",
            "traits": [
                {"name": "Costaud", "value": 3, "note": ""},
                {"name": "Rapide", "value": -2, "note": "sur courte distance"},
            ],
        },
        {
            "label": "Esprit",
            "traits": [
                {"name": "Ruse", "value": None, "note": ""},
            ],
        },
    ]


def _cross_action_payload() -> list[dict[str, Any]]:
    return [
        {
            "name": "Charger",
            # refs: (set=0, trait=0) -> Costaud, (set=1, trait=0) -> Ruse
            "trait_refs": [[0, 0], [1, 0]],
            "condition": "Quand la fuite n'est plus possible",
            "outcome": "L'obstacle cede ou le personnage encaisse",
        }
    ]


@pytest.mark.django_db
class TestCreateCharacterWithSheet:
    def test_creates_character_trait_sets_traits_and_cross_action(
        self, user: User, game: Game
    ) -> None:
        character = create_character_with_sheet(
            user=user,
            name="Aeliana",
            description="Une eclaireuse taciturne",
            origin_game=game,
            sheet_url="https://example.com/sheet",
            avatar=None,
            cover_alt="Une falaise sous la pluie",
            cover_tone="lourde",
            trait_sets=_trait_sets_payload(),
            actions=_cross_action_payload(),
        )

        assert Character.objects.count() == 1
        assert character.status == CharacterStatus.PC
        assert character.owner_id == user.pk
        assert character.creator_id == user.pk
        assert character.origin_game_id == game.pk
        assert character.slug  # auto-generated by Character.save()

        trait_sets = list(TraitSet.objects.filter(character=character).order_by("order"))
        assert len(trait_sets) == 2
        assert [ts.label for ts in trait_sets] == ["Corps", "Esprit"]
        assert [ts.order for ts in trait_sets] == [0, 1]

        traits = Trait.objects.filter(trait_set__character=character)
        assert traits.count() == 3

        corps_traits = list(trait_sets[0].traits.order_by("order"))
        assert [t.name for t in corps_traits] == ["Costaud", "Rapide"]
        assert corps_traits[0].value == 3
        assert corps_traits[1].value == -2
        assert corps_traits[1].note == "sur courte distance"

        esprit_traits = list(trait_sets[1].traits.order_by("order"))
        assert esprit_traits[0].name == "Ruse"
        assert esprit_traits[0].value is None

        actions = Action.objects.filter(character=character)
        assert actions.count() == 1
        action = actions.get()
        assert action.trait_set is None
        assert action.character_id == character.pk
        assert action.condition == "Quand la fuite n'est plus possible"
        assert action.outcome == "L'obstacle cede ou le personnage encaisse"

        linked_trait_names = set(action.traits.values_list("name", flat=True))
        assert linked_trait_names == {"Costaud", "Ruse"}

    def test_out_of_range_trait_value_is_not_rejected(self, user: User, game: Game) -> None:
        """No range validation on Trait.value — deliberately unbounded (model docstring)."""
        trait_sets = [{"label": "Corps", "traits": [{"name": "Epique", "value": 99, "note": ""}]}]

        character = create_character_with_sheet(
            user=user,
            name="Titan",
            description="",
            origin_game=game,
            sheet_url="",
            avatar=None,
            cover_alt="",
            cover_tone="",
            trait_sets=trait_sets,
            actions=[],
        )

        trait = Trait.objects.get(trait_set__character=character)
        assert trait.value == 99

    def test_invalid_trait_ref_rolls_back_everything(self, user: User, game: Game) -> None:
        """An out-of-bounds trait_refs index raises KeyError and rolls back atomically.

        The service deliberately lets this propagate as a natural ``KeyError``
        (documented in ``create_character_with_sheet``'s docstring) rather than
        wrapping it in ``ValidationError`` — Phase 3's view is responsible for
        catching it.
        """
        actions = [
            {
                "name": "Action invalide",
                "trait_refs": [[9, 9]],
                "condition": "",
                "outcome": "",
            }
        ]

        with pytest.raises(KeyError):
            create_character_with_sheet(
                user=user,
                name="Personnage fantome",
                description="",
                origin_game=game,
                sheet_url="",
                avatar=None,
                cover_alt="",
                cover_tone="",
                trait_sets=_trait_sets_payload(),
                actions=actions,
            )

        assert Character.objects.filter(name="Personnage fantome").count() == 0
        assert TraitSet.objects.count() == 0
        assert Trait.objects.count() == 0
        assert Action.objects.count() == 0

    def test_bounded_query_count_does_not_blow_up_with_more_traits(
        self, user: User, game: Game, django_assert_max_num_queries: Any
    ) -> None:
        """Construction loops must not refetch already-held instances (no N+1)."""
        trait_sets = [
            {
                "label": f"Concept {i}",
                "traits": [{"name": f"Trait {i}-{j}", "value": j, "note": ""} for j in range(3)],
            }
            for i in range(4)
        ]
        actions = [
            {
                "name": f"Action {i}",
                "trait_refs": [[0, 0], [1, 1]],
                "condition": "",
                "outcome": "",
            }
            for i in range(3)
        ]

        # 4 trait sets x 3 traits = 12 traits, 3 actions x 2 trait refs each (19
        # objects total). full_clean() issues an FK-existence query per object
        # plus its own insert (and each action's .traits.set() issues one
        # select + one insert) -- ~4 queries/object, so ~80 total is expected
        # and stays linear in object count. What this bound actually guards
        # against is *multiplicative* blow-up: trait_refs resolution reads the
        # in-memory ``traits_by_ref`` map, never re-querying the DB per ref, so
        # adding more actions/trait_refs must not multiply the query count.
        with django_assert_max_num_queries(90):
            create_character_with_sheet(
                user=user,
                name="Concept Multiple",
                description="",
                origin_game=game,
                sheet_url="",
                avatar=None,
                cover_alt="",
                cover_tone="",
                trait_sets=trait_sets,
                actions=actions,
            )


@pytest.fixture
def plain_static(settings: Any) -> None:
    """Swap the manifest static storage for the plain one.

    ``character_create.html`` extends ``base.html``, which resolves hashed
    static assets via the manifest storage — absent in tests (no frontend
    build). The plain backend returns unhashed URLs so full-page renders work
    without ``collectstatic`` (same pattern as ``test_trait_views.py``).
    """
    settings.STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }


@pytest.fixture
def logged_client(client: Client, user: User) -> Client:
    client.force_login(user)
    return client


def _valid_create_payload() -> dict[str, Any]:
    return {
        "trait_sets": [
            {
                "name": "Corps",
                "traits": [{"name": "Costaud", "value": 3, "note": ""}],
            }
        ],
        "actions": [
            {
                "name": "Charger",
                "trait_refs": [[0, 0]],
                "condition": "Quand la fuite n'est plus possible",
                "outcome": "L'obstacle cede",
            }
        ],
    }


@pytest.mark.django_db
class TestCharacterCreateUrl:
    def test_create_url_resolves(self) -> None:
        assert reverse("characters:create") == "/characters/new/"

    def test_new_does_not_match_character_detail(self) -> None:
        match = resolve("/characters/new/")
        assert match.view_name == "characters:create"
        assert match.view_name != "characters:detail"


@pytest.mark.django_db
class TestCharacterCreateViewGet:
    def test_get_renders_200_with_owned_games_only(
        self, plain_static: None, logged_client: Client, user: User, game: Game, other_user: User
    ) -> None:
        other_game = GameFactory(title="Not mine", owner=other_user)  # type: ignore[no-untyped-call]

        url = reverse("characters:create")
        resp = logged_client.get(url)

        assert resp.status_code == 200
        assert game.title.encode() in resp.content
        assert other_game.title.encode() not in resp.content

    def test_anonymous_redirected_to_login(self, client: Client) -> None:
        url = reverse("characters:create")
        resp = client.get(url)
        assert resp.status_code == 302

    def test_renders_alpine_scaffold_and_hidden_payload(
        self, plain_static: None, logged_client: Client, game: Game
    ) -> None:
        """Structural smoke check (Phase 4): the Alpine component is wired up
        and the hidden payload field exists — the actual client-side behavior
        (Alpine state/serialization) cannot be exercised by a server-side test."""
        url = reverse("characters:create")
        resp = logged_client.get(url)
        content = resp.content.decode()

        assert resp.status_code == 200
        assert 'x-data="characterCreate"' in content
        assert '<input type="hidden" name="payload"' in content
        assert ':disabled="!canSubmit"' in content
        assert 'name="origin_game"' in content
        assert 'name="sheet_url"' in content
        # An unrendered {% trans %} tag or a broken quote nesting would leak
        # this literal substring into the response.
        assert "{% trans" not in content


@pytest.mark.django_db
class TestCharacterCreateViewPost:
    def test_valid_post_creates_character_and_redirects(
        self, plain_static: None, logged_client: Client, user: User, game: Game
    ) -> None:
        url = reverse("characters:create")
        resp = logged_client.post(
            url,
            {
                "name": "Aeliana",
                "description": "Une eclaireuse",
                "origin_game": str(game.pk),
                "cover_alt": "Une falaise",
                "cover_tone": "lourde",
                "sheet_url": "https://example.com/sheet",
                "payload": json.dumps(_valid_create_payload()),
            },
        )

        character = Character.objects.get(name="Aeliana")
        assert resp.status_code == 302
        assert resp["Location"] == reverse("characters:detail", kwargs={"slug": character.slug})
        assert character.owner_id == user.pk
        assert character.creator_id == user.pk
        assert character.origin_game_id == game.pk
        assert character.status == CharacterStatus.PC
        assert TraitSet.objects.filter(character=character).count() == 1
        assert Action.objects.filter(character=character).count() == 1

    def test_malformed_payload_renders_422_and_creates_nothing(
        self, plain_static: None, logged_client: Client, game: Game
    ) -> None:
        url = reverse("characters:create")
        resp = logged_client.post(
            url,
            {
                "name": "Fantome",
                "origin_game": str(game.pk),
                "payload": "{not json",
            },
        )

        assert resp.status_code == 422
        assert not Character.objects.filter(name="Fantome").exists()

    def test_oversized_payload_renders_422_and_creates_nothing(
        self, plain_static: None, logged_client: Client, game: Game
    ) -> None:
        url = reverse("characters:create")
        oversized_payload = {
            "trait_sets": [{"name": f"Concept {i}", "traits": []} for i in range(51)],
            "actions": [],
        }
        resp = logged_client.post(
            url,
            {
                "name": "Trop",
                "origin_game": str(game.pk),
                "payload": json.dumps(oversized_payload),
            },
        )

        assert resp.status_code == 422
        assert not Character.objects.filter(name="Trop").exists()

    def test_invalid_trait_ref_renders_422_and_creates_nothing(
        self, plain_static: None, logged_client: Client, game: Game
    ) -> None:
        url = reverse("characters:create")
        payload = {
            "trait_sets": [{"name": "Corps", "traits": [{"name": "Costaud", "value": 3}]}],
            "actions": [
                {
                    "name": "Charger",
                    "trait_refs": [[9, 9]],
                    "condition": "",
                    "outcome": "",
                }
            ],
        }
        resp = logged_client.post(
            url,
            {
                "name": "Fantome2",
                "origin_game": str(game.pk),
                "payload": json.dumps(payload),
            },
        )

        assert resp.status_code == 422
        assert not Character.objects.filter(name="Fantome2").exists()
        assert TraitSet.objects.count() == 0
        assert Trait.objects.count() == 0

    def test_empty_name_renders_422_and_creates_nothing(
        self, plain_static: None, logged_client: Client, game: Game
    ) -> None:
        url = reverse("characters:create")
        resp = logged_client.post(
            url,
            {
                "name": "   ",
                "origin_game": str(game.pk),
                "payload": json.dumps({"trait_sets": [], "actions": []}),
            },
        )

        assert resp.status_code == 422
        assert Character.objects.count() == 0

    def test_non_owned_origin_game_is_rejected(
        self, plain_static: None, logged_client: Client, other_user: User
    ) -> None:
        other_game = GameFactory(title="Not mine", owner=other_user)  # type: ignore[no-untyped-call]

        url = reverse("characters:create")
        resp = logged_client.post(
            url,
            {
                "name": "Intrus",
                "origin_game": str(other_game.pk),
                "payload": json.dumps({"trait_sets": [], "actions": []}),
            },
        )

        assert resp.status_code == 422
        assert not Character.objects.filter(name="Intrus").exists()

    def test_missing_origin_game_renders_422(
        self, plain_static: None, logged_client: Client
    ) -> None:
        url = reverse("characters:create")
        resp = logged_client.post(
            url,
            {
                "name": "Sans partie",
                "payload": json.dumps({"trait_sets": [], "actions": []}),
            },
        )

        assert resp.status_code == 422
        assert Character.objects.count() == 0
