# Generated by Django 5.0.14 on 2026-07-19 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('games', '0024_like_like_unique_user_report_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('summary', "Résumé d'import de scène"), ('link_analysis', 'Analyse de lien'), ('sequence_opening', 'Ouverture de séquence')], max_length=20)),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('resolved', 'Résolue'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='open', max_length=10)),
                ('remote', models.BooleanField(default=False)),
                ('ap_id', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('report', 'linkrequest', 'sharedsequence')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Déclinée')], default='pending', max_length=10)),
                ('remote', models.BooleanField(default=False)),
                ('ap_id', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('created_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.rapport')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_responses', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='offers.socialoffer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialoffer',
            index=models.Index(fields=['content_type', 'object_id'], name='offers_soci_content_5457bf_idx'),
        ),
        migrations.AddIndex(
            model_name='socialoffer',
            index=models.Index(fields=['emitter', 'status'], name='offers_soci_emitter_b65a32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerresponse',
            unique_together={('offer', 'responder')},
        ),
    ]
