# Generated by Django 5.0.14 on 2026-03-06 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKeyCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_url', models.URLField(help_text='Remote actor URL (key owner)', unique=True)),
                ('public_key_pem', models.TextField(help_text='PEM-encoded public key')),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='Last time this key was fetched from remote')),
            ],
            options={
                'verbose_name': 'Clé publique en cache',
                'verbose_name_plural': 'Clés publiques en cache',
                'indexes': [models.Index(fields=['actor_url'], name='pubkey_actor_url_idx')],
            },
        ),
    ]
