# Generated by Django 5.0.14 on 2026-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0002_publickeyache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickeycache',
            name='actor_url',
            field=models.URLField(help_text='Remote actor URL (key owner)', max_length=500, unique=True),
        ),
    ]
