# Generated by Django 5.0.14 on 2026-04-05 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitypub", "0003_publickeyache_url_maxlength"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ap_id",
                    models.URLField(
                        help_text="ActivityPub activity ID (globally unique)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "actor_domain",
                    models.CharField(
                        help_text="Domain of the actor who sent this activity",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité traitée",
                "verbose_name_plural": "Activités traitées",
                "indexes": [
                    models.Index(fields=["ap_id"], name="processed_ap_id_idx"),
                    models.Index(fields=["created_at"], name="processed_created_idx"),
                ],
            },
        ),
    ]
