# Generated by Django 5.0.14 on 2026-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interface_language',
            field=models.CharField(blank=True, default='', help_text='UI language. Empty = use instance default.', max_length=10),
        ),
    ]
