# Generated by Django 5.0.14 on 2026-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_data_is_admin_from_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="muses_post_ingest_optin",
            field=models.BooleanField(
                default=False,
                help_text="Receive an editable summary and federated-link suggestions from Muses when a report is imported from choix-narratifs.",
            ),
        ),
    ]
