# Generated by Django 5.0.14 on 2026-07-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_muses_post_ingest_optin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="muses_credits",
            field=models.PositiveIntegerField(
                default=0, help_text="Available Muses credits."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="muses_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable Muses AI assistance for your account."
            ),
        ),
    ]
