# Generated by Django 5.0.14 on 2026-07-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_muses_credits_user_muses_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='muses_credits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='muses_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='muses_post_ingest_optin',
        ),
    ]
