# Generated by Django 5.0.14 on 2026-04-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_reportcast_character_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="game",
            new_name="games_game_owner_i_2217be_idx",
            old_name="games_game_owner_i_8c7e9a_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="games_game_is_publ_aaf4d5_idx",
            old_name="games_game_is_publ_4e5a6b_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="games_repor_game_id_7c031f_idx",
            old_name="games_repor_game_id_1a2b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="games_repor_status_2d273a_idx",
            old_name="games_repor_status_4d5e6f_idx",
        ),
        migrations.RenameIndex(
            model_name="reportcast",
            new_name="games_repor_report__330046_idx",
            old_name="games_repor_report__7g8h9i_idx",
        ),
    ]
