# Generated by Django 5.2.12 on 2026-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "games",
            "0003_rename_games_game_owner_i_8c7e9a_idx_games_game_owner_i_2217be_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="content_warning",
            field=models.CharField(
                blank=True,
                help_text="Content warning displayed before the report (US-30)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("unlisted", "Non-listé"),
                    ("followers", "Abonnés uniquement"),
                ],
                default="public",
                help_text="Who can see this report (US-29)",
                max_length=20,
            ),
        ),
    ]
