# Generated by Django 5.2.12 on 2026-04-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tag"),
        ("games", "0004_report_content_warning_report_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="core.tag"
            ),
        ),
    ]
