# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_report_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="games/"),
        ),
    ]
