# Generated by Django 5.0.14 on 2026-04-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('git_url', models.URLField(blank=True)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers', 'Followers only')], default='public', help_text='Who can see this report (US-29)', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportcast',
            name='role',
            field=models.CharField(choices=[('main', 'Main'), ('supporting', 'Supporting'), ('mentioned', 'Mentioned')], default='mentioned', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='game_system_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.gamesystem'),
        ),
    ]
