# Generated by Django 5.0.14 on 2026-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_instancesettings'),
        ('games', '0007_gamesystem_alter_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='core.tag'),
        ),
    ]
