# Generated by Django 5.0.14 on 2026-04-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='fr', max_length=10),
        ),
    ]
