# Generated by Django 5.0.14 on 2026-04-29 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_tags_remove_json'),
        ('games', '0009_report_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('description', 'Description'), ('action', 'Action'), ('discussion', 'Discussion'), ('narration', 'Narration')], max_length=20)),
                ('content', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_appearances', to='characters.character')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='games.report')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['report', 'kind'], name='games_rappo_report__e3bdc2_idx')],
            },
        ),
    ]
