# Generated by Django 5.0.14 on 2026-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_report_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': [models.OrderBy(models.F('session_date'), nulls_last=True), models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-created_at']},
        ),
        migrations.AddField(
            model_name='game',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
