# Generated by Django 5.0.14 on 2026-04-29 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_tags_remove_json'),
        ('games', '0010_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('start', 'Start'), ('end', 'End'), ('character_appears', 'Character appears'), ('character_leaves', 'Character leaves'), ('oracle', 'Oracle')], max_length=30)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapport_markers', to='characters.character')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='games.rapport')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['rapport', 'kind'], name='games_rappo_rapport_031292_idx')],
            },
        ),
    ]
