# Generated by Django 5.0.14 on 2026-04-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_started_at_report_session_date'),
        ('games', '0011_rapportmarker'),
    ]

    operations = [
    ]
