# Generated by Django 5.0.14 on 2026-04-29 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_merge_20260429_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_iri', models.URLField(blank=True, max_length=500, null=True)),
                ('parent_rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_links', to='games.rapport')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='games.rapport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rapportlink',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_rapport__isnull', False)), fields=('rapport', 'parent_rapport'), name='unique_local_parent'),
        ),
        migrations.AddConstraint(
            model_name='rapportlink',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_iri__isnull', False)), fields=('rapport', 'parent_iri'), name='unique_remote_parent'),
        ),
    ]
