# Generated by Django 5.0.14 on 2026-07-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_rapportlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="game_system_ref",
        ),
        migrations.DeleteModel(
            name="GameSystem",
        ),
    ]
