# Generated by Django 5.0.14 on 2026-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_rapportlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
