# Generated by Django 5.0.14 on 2026-07-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_remove_game_game_system_ref_delete_gamesystem"),
        ("games", "0014_report_released_at"),
    ]

    operations = []
