# Generated by Django 5.0.14 on 2026-07-08 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_existing_rapports_published(apps, schema_editor):
    """Existing rapports predate the per-rapport draft flow.

    Every rapport that exists before this migration was created directly into a
    live thread (there was no draft state), so it is semantically published.
    Backfill them to ``published`` so they keep rendering in the fil; only new
    rapports created via the composer default to ``draft``.
    """
    Rapport = apps.get_model("games", "Rapport")
    Rapport.objects.update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0011_traitset_trait_action_and_more"),
        ("games", "0015_merge_20260708_0536"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="rapports/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text (a11y + ActivityPub Document.name)",
                        max_length=500,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="rapport",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_existing_rapports_published,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="rapport",
            index=models.Index(
                fields=["report", "status"], name="games_rappo_report__a78e55_idx"
            ),
        ),
        migrations.AddField(
            model_name="rapportmedia",
            name="rapport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="games.rapport",
            ),
        ),
        migrations.AddIndex(
            model_name="rapportmedia",
            index=models.Index(
                fields=["rapport", "order"], name="games_rappo_rapport_f09b56_idx"
            ),
        ),
    ]
