# Generated by Django 5.0.14 on 2026-07-13 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0011_traitset_trait_action_and_more"),
        ("games", "0016_rapportmedia_rapport_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="rapportmedia",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="rapportmedia",
            name="games_rappo_rapport_f09b56_idx",
        ),
        migrations.RemoveField(
            model_name="rapportmedia",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="rapportmedia",
            name="order",
        ),
        migrations.AddField(
            model_name="rapportmedia",
            name="alt",
            field=models.CharField(
                blank=True,
                help_text="Ce que montre l'image (a11y + ActivityPub Document.name).",
                max_length=280,
            ),
        ),
        migrations.AddField(
            model_name="rapportmedia",
            name="tone",
            field=models.CharField(
                blank=True,
                help_text="L'ambiance de l'image : lourde, feutrée…",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="rapportmedia",
            name="image",
            field=models.ImageField(upload_to="rapports/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="rapportmedia",
            name="rapport",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="games.rapport",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="language",
            field=models.CharField(
                default="fr",
                help_text="Langue de la scène, BCP-47 ('fr', 'fr-CA'). Les Rapports en héritent.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="gamecast",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamecast",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="castings",
                to="characters.character",
            ),
        ),
        migrations.AddField(
            model_name="gamecast",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cast",
                to="games.game",
            ),
        ),
        migrations.AddIndex(
            model_name="gamecast",
            index=models.Index(fields=["game"], name="games_gamec_game_id_c5f25c_idx"),
        ),
        migrations.AddConstraint(
            model_name="gamecast",
            constraint=models.UniqueConstraint(
                fields=("game", "character"), name="unique_game_cast"
            ),
        ),
    ]
