# Generated by Django 5.0.14 on 2026-07-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0017_gamecast_alter_rapportmedia_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="released_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
