# Generated by Django 5.0.14 on 2026-07-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_alter_report_released_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rapport",
            name="kind",
            field=models.CharField(
                choices=[
                    ("description", "Description"),
                    ("action", "Action"),
                    ("discussion", "Discussion"),
                    ("narration", "Narration"),
                    ("closure", "Closure"),
                ],
                max_length=20,
            ),
        ),
    ]
