# Generated by Django 5.0.14 on 2026-07-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0012_quote_quote_expires_iff_ephemeral"),
        ("games", "0019_alter_rapport_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rapport",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="rapport",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="rapport",
            index=models.Index(
                fields=["report", "order"], name="games_rappo_report__18e5a0_idx"
            ),
        ),
    ]
