# Generated by Django 5.0.14 on 2026-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0020_alter_rapport_options_rapport_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="muses_summary_proposal",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Draft summary proposed by Muses on import — a proposal, never published as-is.",
            ),
        ),
    ]
