# Generated by Django 5.0.14 on 2026-07-15 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_type'),
        ('games', '0021_report_muses_summary_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='branch_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='previous_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_reports', to='games.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='previous_report_iri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='temporal_anchor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_referrers', to='games.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='temporal_anchor_iri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='temporal_kind',
            field=models.CharField(choices=[('normal', 'Normal'), ('flashback', 'Flashback'), ('flashforward', 'Flashforward')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='temporal_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('previous_report__isnull', False), ('previous_report_iri__gt', ''), _negated=True), name='report_previous_local_xor_remote'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('temporal_anchor__isnull', False), ('temporal_anchor_iri__gt', ''), _negated=True), name='report_anchor_local_xor_remote'),
        ),
    ]
