# Generated by Django 5.0.14 on 2026-07-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_report_fiction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='muses_summary_proposal',
        ),
    ]
