# Generated by Django 5.0.14 on 2026-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_like_like_unique_user_report_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completed_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    'Set once, by close_game(). Once set, every report of this game '
                    'is treated as released, regardless of its own released_at '
                    '(SUD-V1 — see wall_open_q()).'
                ),
                null=True,
            ),
        ),
    ]
