# Generated by Django 5.0.14 on 2026-07-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0026_recommendation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rapportmedia",
            name="tone",
        ),
    ]
