# Generated by Django 5.0.14 on 2026-04-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="character",
            new_name="characters__status_fa26bf_idx",
            old_name="char_status_idx",
        ),
        migrations.RenameIndex(
            model_name="character",
            new_name="characters__origin__54f7de_idx",
            old_name="char_origin_idx",
        ),
        migrations.RenameIndex(
            model_name="character",
            new_name="characters__owner_i_cdb92a_idx",
            old_name="char_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="characterappearance",
            new_name="characters__charact_ea3606_idx",
            old_name="appearance_idx",
        ),
        migrations.RenameIndex(
            model_name="follow",
            new_name="characters__content_d35c70_idx",
            old_name="follow_target_idx",
        ),
        migrations.RenameIndex(
            model_name="follow",
            new_name="characters__followe_b8cc72_idx",
            old_name="follow_follower_idx",
        ),
        migrations.RenameIndex(
            model_name="linkrequest",
            new_name="characters__status_f4bf4e_idx",
            old_name="linkreq_status_idx",
        ),
        migrations.RenameIndex(
            model_name="linkrequest",
            new_name="characters__request_af0d26_idx",
            old_name="linkreq_req_idx",
        ),
        migrations.RenameIndex(
            model_name="quote",
            new_name="characters__charact_7c6a3e_idx",
            old_name="quote_char_vis_idx",
        ),
        migrations.RenameIndex(
            model_name="quote",
            new_name="characters__visibil_36aec6_idx",
            old_name="quote_exp_idx",
        ),
    ]
