# Generated by Django 5.2.12 on 2026-04-05 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characters",
            "0002_rename_char_status_idx_characters__status_fa26bf_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="content_warning",
            field=models.CharField(
                blank=True,
                help_text="Content warning displayed before the quote (US-30)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sharedsequence",
            name="last_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedsequence",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user who edited the content",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sharedsequence",
            name="publication_proposed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedsequence",
            name="publication_proposed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who proposed publishing (needs both parties to validate)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="linkrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("queued", "En file d'attente"),
                    ("accepted", "Acceptée"),
                    ("rejected", "Refusée"),
                    ("cancelled", "Annulée"),
                    ("expired", "Expirée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
