# Generated by Django 5.2.12 on 2026-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characters",
            "0003_quote_content_warning_sharedsequence_last_edited_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name, auto-generated from name",
                max_length=120,
            ),
        ),
        # FTS index for character search (US-07)
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_character_fts
                ON characters_character
                USING gin(
                    to_tsvector('french', coalesce(name, '') || ' ' || coalesce(description, ''))
                );
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_character_fts;",
        ),
    ]
