# Generated by Django 5.2.12 on 2026-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_add_slug_and_fts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name, auto-generated from name",
                max_length=120,
                unique=True,
            ),
        ),
    ]
