# Generated by Django 5.0.14 on 2026-04-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_tags'),
        ('core', '0004_add_instancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='tags_new',
            field=models.ManyToManyField(blank=True, related_name='characters', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('npc', 'NPC'), ('pc', 'PC'), ('claimed', 'Claimed'), ('adopted', 'Adopted'), ('forked', 'Forked')], default='npc', max_length=20),
        ),
        migrations.AlterField(
            model_name='characterappearance',
            name='role',
            field=models.CharField(choices=[('main', 'Main'), ('supporting', 'Supporting'), ('mentioned', 'Mentioned')], default='mentioned', max_length=20),
        ),
        migrations.AlterField(
            model_name='characterlink',
            name='type',
            field=models.CharField(choices=[('claim', 'Claim (retcon)'), ('adopt', 'Adoption'), ('fork', 'Fork (derivation)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='linkrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='linkrequest',
            name='type',
            field=models.CharField(choices=[('claim', 'Claim (retcon)'), ('adopt', 'Adoption'), ('fork', 'Fork (derivation)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='visibility',
            field=models.CharField(choices=[('ephemeral', 'Ephemeral'), ('private', 'Private'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedsequence',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
