# Generated by Django 5.0.14 on 2026-05-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_tags_remove_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlink',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='characterlink',
            index=models.Index(fields=['status'], name='characters__status_4f658a_idx'),
        ),
    ]
