# Generated by Django 5.0.14 on 2026-07-07 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0010_characterlink_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraitSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        default="Traits",
                        help_text="Free-form label (e.g. Traits, Aspects, Thèmes)",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_sets",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Free-form trait name (e.g. Casse-cou, Sworn to the crown)",
                        max_length=200,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True,
                        help_text="Display value on the sheet. Nullable for valueless tags. Never evaluated.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional fiction attached to the trait"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "trait_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traits",
                        to="characters.traitset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Free-form action name (e.g. Foncer dans le tas, Convaincre)",
                        max_length=200,
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="When this action applies — displayed text, never evaluated",
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="What the action produces — displayed text, never evaluated",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "traits",
                    models.ManyToManyField(
                        blank=True,
                        help_text="One or more traits this action draws on",
                        related_name="actions",
                        to="characters.trait",
                    ),
                ),
                (
                    "trait_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="characters.traitset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="traitset",
            index=models.Index(
                fields=["character"], name="characters__charact_da3a6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trait",
            index=models.Index(
                fields=["trait_set"], name="characters__trait_s_37a2fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["trait_set"], name="characters__trait_s_03df6a_idx"
            ),
        ),
    ]
