# Generated by Django 5.0.14 on 2026-07-14 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0011_traitset_trait_action_and_more"),
        ("games", "0018_alter_report_released_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("expires_at__isnull", False), ("visibility", "ephemeral")
                    ),
                    models.Q(
                        models.Q(("visibility", "ephemeral"), _negated=True),
                        ("expires_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="quote_expires_iff_ephemeral",
            ),
        ),
    ]
