# Generated by Django 5.0.14 on 2026-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_quote_quote_expires_iff_ephemeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Ce que montre la couverture (a11y + ActivityPub Document.name).', max_length=280),
        ),
        migrations.AddField(
            model_name='character',
            name='cover_tone',
            field=models.CharField(blank=True, help_text="L'ambiance de la couverture : lourde, feutrée…", max_length=80),
        ),
    ]
