# Generated by Django 5.0.14 on 2026-07-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_character_cover_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='characters.character'),
        ),
    ]
