# Generated by Django 5.0.14 on 2026-07-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_action_character_finalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('npc', 'NPC'), ('pc', 'PC'), ('claimed', 'Claimed'), ('adopted', 'Adopted')], default='npc', max_length=20),
        ),
    ]
