# Generated by Django 5.0.14 on 2026-07-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_alter_character_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkrequest',
            name='origin_offer_id',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
