# Generated by Django 5.0.14 on 2026-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_linkrequest_origin_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='accepted',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
