# Generated by Django 5.0.14 on 2026-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_follow_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='auto',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    'AUTO = created by the cast auto-follow sync (Epic D, #134): a '
                    'shared GameCast/GM membership justifies it, and it is recomputed '
                    'away when that membership ends. MANUEL (default False) = created '
                    'by the follow button — always survives cast teardown.'
                ),
            ),
        ),
    ]
