# Generated by Django 5.0.14 on 2026-07-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0020_follow_auto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="cover_tone",
        ),
    ]
