# Generated by Django 5.0.14 on 2026-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0021_remove_character_cover_tone"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="background",
            field=models.TextField(
                blank=True, help_text="Public backstory / lore shown on the sheet."
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="secrets",
            field=models.TextField(
                blank=True,
                help_text="Maintainer-only notes (creator/owner). Never shown publicly.",
            ),
        ),
    ]
