# Generated by Django 5.0.14 on 2026-07-21 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0022_character_background_character_secrets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        help_text="Displayed condition label (e.g. 7-9). Free text, never evaluated.",
                        max_length=100,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The result — displayed text, never evaluated"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="characters.action",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="characters__action__d17ebc_idx"
                    )
                ],
            },
        ),
    ]
