# Generated by Django 5.0.14 on 2026-07-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0023_actionoutcome"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Quote",
        ),
    ]
