# Generated by Django 5.0.14 on 2026-07-26 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0024_delete_quote"),
        ("core", "0011_remove_userusagestats_total_quotes"),
        ("games", "0027_remove_rapportmedia_tone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived characters are hidden from public lists but kept (reversible).",
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                fields=["is_archived"], name="characters__is_arch_8e1592_idx"
            ),
        ),
    ]
