# Generated by Django 5.0.14 on 2026-07-16 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FediverseApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance", models.CharField(max_length=255, unique=True)),
                ("software", models.CharField(blank=True, default="", max_length=50)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("redirect_uri", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fediverse app",
                "verbose_name_plural": "Fediverse apps",
            },
        ),
        migrations.CreateModel(
            name="FediverseAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance", models.CharField(db_index=True, max_length=255)),
                ("uid", models.CharField(max_length=255)),
                ("acct", models.CharField(max_length=512)),
                ("url", models.URLField(blank=True, default="")),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fediverse_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fediverse account",
                "verbose_name_plural": "Fediverse accounts",
            },
        ),
        migrations.AddConstraint(
            model_name="fediverseaccount",
            constraint=models.UniqueConstraint(
                fields=("instance", "uid"), name="unique_fediverse_identity"
            ),
        ),
    ]
