#!/usr/bin/env python3
"""Generate aidd_docs/KNOWLEDGE.md from memory bank files."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MEMORY_DIR = ROOT / "aidd_docs" / "memory"
OUTPUT = ROOT / "aidd_docs" / "KNOWLEDGE.md"


def extract_description(path: Path) -> str:
    """Extract first heading or first non-empty line as description."""
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            # Skip empty lines and HTML comments
            if not stripped or stripped.startswith("<!--"):
                continue
            # Use heading text without #
            if stripped.startswith("#"):
                return stripped.lstrip("#").strip()
            # Fallback to first non-empty line
            return stripped
    except Exception:
        pass
    return "-"


def collect_files(directory: Path) -> list[Path]:
    """Collect .md files sorted alphabetically, excluding .gitkeep."""
    return sorted(f for f in directory.iterdir() if f.suffix == ".md")


def render_table(files: list[Path], rel_base: Path) -> str:
    """Render a markdown table from a list of files."""
    lines = ["| File | Description |", "|------|-------------|"]
    for f in files:
        rel = f.relative_to(rel_base).as_posix()
        desc = extract_description(f)
        lines.append(f"| [{f.name}]({rel}) | {desc} |")
    return "\n".join(lines)


def main() -> None:
    sections: list[str] = []

    # Header
    sections.append("# Memory Bank Knowledge\n")
    sections.append(
        "Project-specific knowledge files: architecture, standards, and reference documentation.\n"
    )
    sections.append("> Auto-generated by `scripts/generate_knowledge.py`.\n")

    # Root memory files
    root_files = collect_files(MEMORY_DIR)
    if root_files:
        sections.append("## Memory\n")
        sections.append(render_table(root_files, MEMORY_DIR))

    # Subdirectories
    for subdir in sorted(MEMORY_DIR.iterdir()):
        if not subdir.is_dir():
            continue
        sub_files = collect_files(subdir)
        if sub_files:
            sections.append(f"\n### `memory/{subdir.name}`\n")
            sections.append(render_table(sub_files, MEMORY_DIR))

    content = "\n".join(sections) + "\n"

    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
